services:
    frontend:
        build: frontend/
        ports:
            - '80:80'
        depends_on:
            - backend

    backend:
        build: backend/
        ports:
            - '5000:5000'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydatabase
            POSTGRES_HOST: db
        depends_on:
            db:
                condition: service_healthy
                restart: true

    db:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydatabase
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

volumes:
    postgres_data:
